export const serviceLines = [
  {
    id: 1,
    name: "Janitorial",
  },
  {
    id: 4,
    name: "Landscaping",
  },
  {
    id: 7,
    name: "Landscape Construction",
  },
  {
    id: 3,
    name: "Lot Sweeping",
  },
  {
    id: 2,
    name: "Snow",
  },
  {
    id: 5,
    name: "Asphalt",
  },
  {
    id: 46,
    name: "On Demand",
  },
  {
    id: 6,
    name: "HVAC",
  },
];

export const softwares = [
  "No Portal",
  "Corrigo",
  "Coupa",
  "EcoTrak",
  "KBP (VX Suite)",
  "Limble",
  "MaintainX",
  "Nest",
  "Potfolio",
  "Procursys",
  "Ramp Public Storage",
  "Service One (GPM)",
  "ServiceChannel",
  "SiteFotos",
  "Verisae",
  "Wrench",
];

export const serviceLineServices = {
  "On Demand": [],
  "General Services": [],
  Snow: [
    "Lot Snow Removal Rate",
    "Lot Deicing",
    "Walkway Snow Removal Rate",
    "Walkway Deicing",
    "Municipal Snow Removal Rate",
    "Municipal Deicing",
    "Front Loader",
    "Hauling",
    "Bobcat",
    "Dump Truck",
    "Dump Trailer",
    "Skidsteer",
    "Roof/Gas Canopy Shoveling",
    "Snow Raking Roofline",
    "Snow Shoveling",
    "Snow Stacking",
    "Deicing Entire Grounds",
    "Material",
  ],
  "Lot Sweeping": [
    "Lot Sweeping Rate",
    "Portering Rate",
    "Lot Pressure Washing Rate",
    "Walkway Pressure Washing Rate",
  ],
  Landscaping: [
    "Routine Maintenance Rate",
    "Mulch Rate",
    "Fertilizer Rate",
    "Pruning Rate",
    "Irrigation On/Off (Includes Fall Blowout) Rate",
    "Spring Cleanup Rate",
    "Fall Cleanup Rate",
    "Aeration/Overseed (Fall) Rate",
    "Storm/Emergency Cleanup Rate",
    "Turf Management Rate",
    "Pre Emergent",
    "Wet Test",
    "Irrigation On Rate",
    "Irrigation Off Rate",
  ],
  "Landscape Construction": [],
};
